workflows:
  upload_to_internal_test_aab:
    name: Upload to Internal Test AAB
#    instance_type: linux
    max_build_duration: 15
    environment:
      groups:
        - google_credentials
        - android_credentials
      flutter: 3.44.4
    scripts:
      - name: Restore key
        script: |
          echo $KEY_PROPERTY > android/key.properties
          echo  "$UPLOAD_KEYSTORE_BASE64" | base64 --decode > android/app/upload-keystore.jks
          pwd
          ls -la android/key.properties
          ls -la android/app/upload-keystore.jks
      - name: Clean Flutter project
        script: |
          flutter clean
      - name: Get Flutter packages
        script: |
          flutter pub get
      - name: Flutter build appbundle
        script: |
          flutter build appbundle --release
    artifacts:
      - build/app/outputs/bundle/release/
    publishing:
      google_play:

        credentials: $GOOGLE_PLAY_SERVICE_ACCOUNT_CREDENTIALS

        track: internal

        release_name: Test AAB

