// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:spend_lens/core/hive/hive_adapters.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(AppSettingsAdapter());
    registerAdapter(CategoryAdapter());
    registerAdapter(ExpenseAdapter());
    registerAdapter(PriceObservationAdapter());
    registerAdapter(ProductAdapter());
    registerAdapter(ReceiptAdapter());
    registerAdapter(ReceiptItemAdapter());
    registerAdapter(StoreAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(AppSettingsAdapter());
    registerAdapter(CategoryAdapter());
    registerAdapter(ExpenseAdapter());
    registerAdapter(PriceObservationAdapter());
    registerAdapter(ProductAdapter());
    registerAdapter(ReceiptAdapter());
    registerAdapter(ReceiptItemAdapter());
    registerAdapter(StoreAdapter());
  }
}
